export const DEFAULT_BUILTIN_COMPONENTS = [
  {
    key: 'Card',
    value: {
      props: {
        type: 'raised',
        insetScale: 'm',
        theme: 'light',
        className: '',
        children: '',
        onClick: '',
        to: '',
        isExternalLink: '',
        isDisabled: '',
      },
      propsBindings: {
        type: {
          value: 'raised',
          dataType: 'string',
          type: 'property',
          sortOrder: 0.9,
        },
        insetScale: {
          value: 'm',
          dataType: 'string',
          type: 'property',
        },
        theme: {
          value: 'light',
          dataType: 'string',
          type: 'property',
        },
        className: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        children: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        onClick: {
          value: '',
          dataType: 'event',
          type: 'property',
        },
        to: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        isExternalLink: {
          value: '',
          dataType: 'boolean',
          type: 'property',
        },
        isDisabled: {
          value: '',
          dataType: 'boolean',
          type: 'property',
        },
      },
    },
  },
  {
    key: 'TextInput',
    value: {
      props: {
        id: '',
        autoComplete: '',
        'aria-invalid': '',
        'aria-errormessage': '',
        className: '',
        name: '',
        value: '',
        onChange: '',
        onBlur: '',
        onFocus: '',
        isAutofocussed: '',
        isCondensed: '',
        isDisabled: '',
        isReadOnly: '',
        hasError: '',
        hasWarning: '',
        placeholder: '',
        horizontalConstraint: 'scale',
      },
      propsBindings: {
        id: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        autoComplete: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        'aria-invalid': {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        'aria-errormessage': {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        className: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        name: {
          value: '',
          dataType: 'string',
          type: 'property',
          sortOrder: 0.9,
        },
        value: {
          value: '',
          dataType: 'string',
          type: 'property',
          sortOrder: 0.9,
        },
        onChange: {
          value: '',
          dataType: 'event',
          type: 'property',
        },
        onBlur: {
          value: '',
          dataType: 'event',
          type: 'property',
        },
        onFocus: {
          value: '',
          dataType: 'event',
          type: 'property',
        },
        isAutofocussed: {
          value: '',
          dataType: 'boolean',
          type: 'property',
        },
        isCondensed: {
          value: '',
          dataType: 'boolean',
          type: 'property',
        },
        isDisabled: {
          value: '',
          dataType: 'boolean',
          type: 'property',
        },
        isReadOnly: {
          value: '',
          dataType: 'boolean',
          type: 'property',
        },
        hasError: {
          value: '',
          dataType: 'boolean',
          type: 'property',
        },
        hasWarning: {
          value: '',
          dataType: 'boolean',
          type: 'property',
        },
        placeholder: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        horizontalConstraint: {
          value: 'scale',
          dataType: 'string',
          type: 'property',
        },
      },
    },
  },
  {
    key: 'TextField',
    value: {
      props: {
        id: '',
        horizontalConstraint: 'scale',
        errors: '',
        warnings: '',
        renderError: '',
        renderWarning: '',
        isRequired: '',
        touched: '',
        autoComplete: '',
        name: '',
        value: '',
        onChange: '',
        onBlur: '',
        onFocus: '',
        isAutofocussed: '',
        isCondensed: '',
        isDisabled: '',
        isReadOnly: '',
        placeholder: '',
        title: '',
        hint: '',
        description: '',
        onInfoButtonClick: '',
        hintIcon: '',
        badge: '',
      },
      propsBindings: {
        id: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        horizontalConstraint: {
          value: 'scale',
          dataType: 'string',
          type: 'property',
        },
        errors: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        warnings: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        renderError: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        renderWarning: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        isRequired: {
          value: '',
          dataType: 'boolean',
          type: 'property',
        },
        touched: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        autoComplete: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        name: {
          value: '',
          dataType: 'string',
          type: 'property',
          sortOrder: 0.9,
        },
        value: {
          value: '',
          dataType: 'string',
          type: 'property',
          sortOrder: 0.9,
        },
        onChange: {
          value: '',
          dataType: 'event',
          type: 'property',
        },
        onBlur: {
          value: '',
          dataType: 'event',
          type: 'property',
        },
        onFocus: {
          value: '',
          dataType: 'event',
          type: 'property',
        },
        isAutofocussed: {
          value: '',
          dataType: 'boolean',
          type: 'property',
        },
        isCondensed: {
          value: '',
          dataType: 'boolean',
          type: 'property',
        },
        isDisabled: {
          value: '',
          dataType: 'boolean',
          type: 'property',
        },
        isReadOnly: {
          value: '',
          dataType: 'boolean',
          type: 'property',
        },
        placeholder: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        title: {
          value: '',
          dataType: 'string',
          type: 'property',
          sortOrder: 0.9,
        },
        hint: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        description: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        onInfoButtonClick: {
          value: '',
          dataType: 'event',
          type: 'property',
        },
        hintIcon: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        badge: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
      },
    },
  },
  {
    key: 'Text.Wrap',
    value: {
      props: {
        id: '',
        intlMessage: '',
        children: '',
        title: '',
      },
      propsBindings: {
        id: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        intlMessage: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        children: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        title: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
      },
    },
  },
  {
    key: 'Text.Subheadline',
    value: {
      props: {
        as: '',
        truncate: '',
        nowrap: '',
        isBold: '',
        tone: '',
        id: '',
        intlMessage: '',
        children: '',
        title: '',
      },
      propsBindings: {
        as: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        truncate: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        nowrap: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        isBold: {
          value: '',
          dataType: 'boolean',
          type: 'property',
        },
        tone: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        id: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        intlMessage: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        children: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        title: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
      },
    },
  },
  {
    key: 'Text.Headline',
    value: {
      props: {
        as: '',
        truncate: '',
        nowrap: '',
        id: '',
        intlMessage: '',
        children: '',
        title: '',
      },
      propsBindings: {
        as: {
          value: '',
          dataType: 'string',
          type: 'property',
          sortOrder: 0.9,
        },
        truncate: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        nowrap: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        id: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        intlMessage: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        children: {
          value: '',
          dataType: 'string',
          type: 'property',
          sortOrder: 0.9,
          hint: 'Enter text here',
        },
        title: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
      },
    },
  },
  {
    key: 'Text.Detail',
    value: {
      props: {
        isBold: '',
        isItalic: '',
        isStrikethrough: '',
        as: '',
        tone: '',
        fontWeight: '',
        truncate: '',
        nowrap: '',
        'aria-labelledby': '',
        id: '',
        intlMessage: '',
        children: '',
        title: '',
      },
      propsBindings: {
        isBold: {
          value: '',
          dataType: 'boolean',
          type: 'property',
        },
        isItalic: {
          value: '',
          dataType: 'boolean',
          type: 'property',
        },
        isStrikethrough: {
          value: '',
          dataType: 'boolean',
          type: 'property',
        },
        as: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        tone: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        fontWeight: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        truncate: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        nowrap: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        'aria-labelledby': {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        id: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        intlMessage: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        children: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        title: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
      },
    },
  },
  {
    key: 'Text.Caption',
    value: {
      props: {
        isItalic: '',
        isStrikethrough: '',
        tone: '',
        fontWeight: '',
        truncate: '',
        nowrap: '',
        'aria-labelledby': '',
        id: '',
        intlMessage: '',
        children: '',
        title: '',
      },
      propsBindings: {
        isItalic: {
          value: '',
          dataType: 'boolean',
          type: 'property',
        },
        isStrikethrough: {
          value: '',
          dataType: 'boolean',
          type: 'property',
        },
        tone: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        fontWeight: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        truncate: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        nowrap: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        'aria-labelledby': {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        id: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        intlMessage: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        children: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        title: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
      },
    },
  },
  {
    key: 'Text.Body',
    value: {
      props: {
        as: '',
        isBold: '',
        isItalic: '',
        isStrikethrough: '',
        tone: '',
        fontWeight: '',
        truncate: '',
        nowrap: '',
        id: '',
        intlMessage: '',
        children: '',
        title: '',
      },
      propsBindings: {
        as: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        isBold: {
          value: '',
          dataType: 'boolean',
          type: 'property',
        },
        isItalic: {
          value: '',
          dataType: 'boolean',
          type: 'property',
        },
        isStrikethrough: {
          value: '',
          dataType: 'boolean',
          type: 'property',
        },
        tone: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        fontWeight: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        truncate: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        nowrap: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        id: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        intlMessage: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        children: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        title: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
      },
    },
  },
  {
    container: 'COMPOSE_IT_component_props',
    key: 'PrimaryButton',
    value: {
      props: {
        as: '',
        type: 'button',
        label: '',
        iconLeft: '',
        isToggleButton: '',
        isToggled: '',
        isDisabled: '',
        onClick: '',
        size: '20',
        tone: 'primary',
      },
      propsBindings: {
        as: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        type: {
          value: 'button',
          dataType: 'string',
          type: 'property',
        },
        label: {
          value: '',
          dataType: 'string',
          type: 'property',
          sortOrder: 0.9,
        },
        iconLeft: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        isToggleButton: {
          value: '',
          dataType: 'boolean',
          type: 'property',
        },
        isToggled: {
          value: '',
          dataType: 'boolean',
          type: 'property',
        },
        isDisabled: {
          value: '',
          dataType: 'boolean',
          type: 'property',
        },
        onClick: {
          value: '',
          dataType: 'event',
          type: 'property',
          sortOrder: 0.9,
        },
        size: {
          value: '20',
          dataType: 'string',
          type: 'property',
        },
        tone: {
          value: 'primary',
          dataType: 'string',
          type: 'property',
        },
      },
    },
  },
  {
    key: 'Link',
    value: {
      props: {
        children: '',
        intlMessage: '',
        isExternal: '',
        to: '',
        tone: 'primary',
        onClick: '',
      },
      propsBindings: {
        children: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        intlMessage: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        isExternal: {
          value: '',
          dataType: 'boolean',
          type: 'property',
        },
        to: {
          value: '',
          dataType: 'string',
          type: 'property',
          sortOrder: 0.9,
        },
        tone: {
          value: 'primary',
          dataType: 'string',
          type: 'property',
        },
        onClick: {
          value: '',
          dataType: 'event',
          type: 'property',
        },
      },
    },
  },
  {
    key: 'FormModalPage',
    value: {
      props: {
        level: '',
        title: '',
        isOpen: '',
        onClose: '',
        customViewLocatorCode: '',
        children: '',
        zIndex: '',
        baseZIndex: '',
        getParentSelector: '',
        shouldDelayOnClose: '',
        afterOpenStyles: '',
        topBarCurrentPathLabel: '',
        topBarPreviousPathLabel: '',
        subtitle: '',
        isPrimaryButtonDisabled: '',
        isSecondaryButtonDisabled: '',
        dataAttributesPrimaryButton: '',
        dataAttributesSecondaryButton: '',
        labelPrimaryButton: '',
        labelSecondaryButton: '',
        onPrimaryButtonClick: '',
        onSecondaryButtonClick: '',
        hideControls: '',
        iconLeftSecondaryButton: '',
      },
      propsBindings: {
        level: {
          value: '',
          dataType: 'string',
          type: 'property',
          sortOrder: 0.9,
        },
        title: {
          value: '',
          dataType: 'string',
          type: 'property',
          sortOrder: 0.9,
        },
        isOpen: {
          value: '',
          dataType: 'boolean',
          type: 'property',
        },
        onClose: {
          value: '',
          dataType: 'event',
          type: 'property',
        },
        customViewLocatorCode: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        children: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        zIndex: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        baseZIndex: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        getParentSelector: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        shouldDelayOnClose: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        afterOpenStyles: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        topBarCurrentPathLabel: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        topBarPreviousPathLabel: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        subtitle: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        isPrimaryButtonDisabled: {
          value: '',
          dataType: 'boolean',
          type: 'property',
        },
        isSecondaryButtonDisabled: {
          value: '',
          dataType: 'boolean',
          type: 'property',
        },
        dataAttributesPrimaryButton: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        dataAttributesSecondaryButton: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        labelPrimaryButton: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        labelSecondaryButton: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        onPrimaryButtonClick: {
          value: '',
          dataType: 'event',
          type: 'property',
        },
        onSecondaryButtonClick: {
          value: '',
          dataType: 'event',
          type: 'property',
        },
        hideControls: {
          value: '',
          dataType: 'boolean',
          type: 'property',
        },
        iconLeftSecondaryButton: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
      },
    },
  },
  {
    key: 'FormDetailPage',
    value: {
      props: {
        title: '',
        subtitle: '',
        customTitleRow: '',
        customViewLocatorCode: '',
        children: '',
        previousPathLabel: '',
        onPreviousPathClick: '',
        isPrimaryButtonDisabled: '',
        isSecondaryButtonDisabled: '',
        dataAttributesPrimaryButton: '',
        dataAttributesSecondaryButton: '',
        labelPrimaryButton: '',
        labelSecondaryButton: '',
        onPrimaryButtonClick: '',
        onSecondaryButtonClick: '',
        hideControls: '',
        iconLeftSecondaryButton: '',
      },
      propsBindings: {
        title: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        subtitle: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        customTitleRow: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        customViewLocatorCode: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        children: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        previousPathLabel: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        onPreviousPathClick: {
          value: '',
          dataType: 'event',
          type: 'property',
        },
        isPrimaryButtonDisabled: {
          value: '',
          dataType: 'boolean',
          type: 'property',
        },
        isSecondaryButtonDisabled: {
          value: '',
          dataType: 'boolean',
          type: 'property',
        },
        dataAttributesPrimaryButton: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        dataAttributesSecondaryButton: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        labelPrimaryButton: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        labelSecondaryButton: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        onPrimaryButtonClick: {
          value: '',
          dataType: 'event',
          type: 'property',
        },
        onSecondaryButtonClick: {
          value: '',
          dataType: 'event',
          type: 'property',
        },
        hideControls: {
          value: '',
          dataType: 'boolean',
          type: 'property',
        },
        iconLeftSecondaryButton: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
      },
    },
  },
  {
    key: 'Form',
    value: {
      props: {
        onAction: '',
        initialData: '',
      },
      propsBindings: {
        onAction: {
          value: '',
          dataType: 'event',
          type: 'property',
          sortOrder: 0.9,
        },
        initialData: {
          value: '',
          dataType: 'string',
          type: 'property',
          sortOrder: 0.9,
          hint: 'Select a datasource ',
        },
      },
    },
  },
  {
    key: 'Loop',
    value: {
      props: {
        data: '',
      },
      propsBindings: {
        data: {
          value: [],
          dataType: 'array',
          type: 'property',
          sortOrder: 0.9,
          hint: 'Select an array',
        },
      },
    },
  },
  {
    key: 'DataTable',
    value: {
      props: {
        rows: [],
        columns: [],
        footer: '',
        maxWidth: '',
        maxHeight: '',
        onRowClick: '',
        isCondensed: true,
        onColumnResized: '',
        disableSelfContainment: '',
        disableHeaderStickiness: '',
        wrapHeaderLabels: true,
        verticalCellAlignment: 'top',
        horizontalCellAlignment: 'left',
        sortedBy: '',
        onSortChange: '',
        sortDirection: '',
      },
      propsBindings: {
        rows: {
          type: 'property',
          dataType: 'array',
          value: [],
          sortOrder: 0.9,
        },
        columns: {
          type: 'property',
          dataType: 'array',
          value: [],
          sortOrder: 0.9,
        },
        footer: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        maxWidth: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        maxHeight: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        onRowClick: {
          value: '',
          dataType: 'event',
          type: 'property',
          sortOrder: 0.9,
        },
        isCondensed: {
          value: true,
          dataType: 'boolean',
          type: 'property',
        },
        onColumnResized: {
          value: '',
          dataType: 'event',
          type: 'property',
        },
        disableSelfContainment: {
          value: '',
          dataType: 'boolean',
          type: 'property',
        },
        disableHeaderStickiness: {
          value: '',
          dataType: 'boolean',
          type: 'property',
        },
        itemRenderer: {
          dataType: 'function',
          type: 'property',
        },
        wrapHeaderLabels: {
          value: true,
          dataType: 'boolean',
          type: 'property',
        },
        verticalCellAlignment: {
          value: 'top',
          dataType: 'string',
          type: 'property',
        },
        horizontalCellAlignment: {
          value: 'left',
          dataType: 'string',
          type: 'property',
        },
        sortedBy: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
        onSortChange: {
          value: '',
          dataType: 'event',
          type: 'property',
        },
        sortDirection: {
          value: '',
          dataType: 'string',
          type: 'property',
        },
      },
    },
  },
];
